# Generated by Django 4.2.2 on 2023-06-19 16:17

import car_collection.car.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sports Car', 'Sports Car'), ('Pickup', 'Pickup'), ('Crossover', 'Crossover'), ('Minibus', 'Minibus'), ('Other', 'Other')], max_length=10)),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'It should consist of a minimum of 2 characters.')])),
                ('year', models.IntegerField(validators=[car_collection.car.validators.years_validator])),
                ('image_url', models.ImageField(upload_to='')),
                ('price', models.FloatField(validators=[django.core.validators.MinLengthValidator(1, 'Price cannot be below 1.')])),
            ],
        ),
    ]
